### ISSUE TITLE
Dependencies of Dependencies not available to npm installed modules

### ISSUE THREAD

**Issue by idkjs** [Sunjammer/nfuse#21]
So I tried this. Seems promising but didnt quite work.  i npm installed nfuse and apollo-client, required apollo-client and Fuse saw it. Big victory there. Apollo-client uses lodash. Lodash and everything apolloclient is dependent on is in the node-modules folder but on the same level as apollo-client. When the apollo-client code runs, it refers to the those folders which it did not nfuse because i didnt install them. Seems like it only runs the nfuse on the install dependency but not the dependencies dependencies. 

Just for fun I npm installed all of the apollo-client dependecies directly in my package.json file. This got past some of the original 'module not found' errors but started having problems with more deeply nested require statement. For example, graphql-tag/printer is required in apollo-client/index.js and its not resolving. I tried changing the path but cant get it to go. Needless to say, chasing all of them down is not practical. 

From Fuse Monitor:
`LOG: Error: JavaScript error in apollo-client line 5. require(): module not found: graphql-tag/printer in Fuse.Scripting.ScriptModule+RequireContext</usr/local/share/uno/Packages/Fuse.Scripting/0.38.6/$.uno:214>`

also, the runkit example on the npmjs.com site doesnt recognize the fuse package. FYI. https://runkit.com/npm/nfuse

**Comment by idkjs** [comment]
Ok. So just to keep a record on chasing this down. After getting module not found for apollo-clients dependencies, i added all of apollo-client's dependencies from its package.json file to the projects root package.json file so that nfuse will see them. Why did I do this? If you run nfuse on apollo-client, your /NPM-Packages will only produce a Lib_apollo_client for the global object to be aware of. If any of apollo-client's dependencies use a require statement, the required module will not have been processed by nfuse and thus, it will not be available in the ux:GlobalModule. 

What happened. After taking https://github.com/apollostack/apollo-client/blob/master/package.json and adding all the dependencies to my project root package.json, in addition to apollo-client, i ran nfuse in terminal. You then get a ux:GlobalModule lib for each one of the dependencies. When you run the project with fuse preview, the previous error is gone and now you get another errror, for the exact same scenario in the project. So the idea then, is that you would have to go through this process for every package.json in every dependency and all of its dependencies.

Starting with lodash, including all of lodash produced a compile error `FATAL ERROR: Too many open files (pass --trace for stack trace)` with 1086 Includes in the unoproj. So I figured i would work through the errors and just add required sub modules. Turns out that apollo is calling the lodash submodules with dot notation. NFuse doesnt appear to be processing these. This is the error

 `LOG: Error: JavaScript error in ../node_modules/apollo-client/transport/networkInterface line 2. require(): module not found: lodash.isstring in Fuse.Scripting.ScriptModule+RequireContext</usr/local/share/uno/Packages/Fuse.Scripting/0.39.3/$.uno:214>`

 The apollo-client dependencies using dot notation can be seen here:

 `"dependencies": {
    "graphql-anywhere": "^0.2.4",
    "graphql-tag": "^0.1.13",
    "lodash.assign": "^4.0.8",
    "lodash.clonedeep": "^4.3.2",
    "lodash.countby": "^4.4.0",
    "lodash.flatten": "^4.2.0",
    "lodash.forown": "^4.1.0",
    "lodash.has": "^4.3.1",
    "lodash.identity": "^3.0.0",
    "lodash.includes": "^4.1.2",
    "lodash.isboolean": "^3.0.3",
    "lodash.isequal": "^4.2.0",
    "lodash.isnull": "^3.0.0",
    "lodash.isnumber": "^3.0.3",
    "lodash.isobject": "^3.0.2",
    "lodash.isstring": "^4.0.1",
    "lodash.isundefined": "^3.0.1",
    "lodash.mapvalues": "^4.4.0",
    "lodash.merge": "^4.6.0",
    "lodash.pick": "^4.2.0",
    "redux": "^3.3.1",
    "symbol-observable": "^1.0.2",
    "whatwg-fetch": "^1.0.0"
  },` 

Seems like an easy fix, once i learn enough js....

**Comment by gtoto007** [comment]
I also had the same problem when I included an npm dependency that in turn required additional dependencies. This issue makes nfuse unusable.

**Comment by Sunjammer** [comment]
Thanks for the detailed reporting guys, I hate to be **That Open Source Guy** but I'm swamped in other stuff these days including a lot of travel. I'll look at it as soon as I have a quiet moment but if any of y'all want to have a look and throw me a pull request I would really appreciate it! Team effort etc etc.

Just to give an overview of the issue of dependencies, npm require is not commonjs, it is node specific. Everybody trying for npm compat has to work around how npm require works. Fuse itself does a lot of gymnastics to ensure require statements come through in a sensible way.

NFuse tries to help Fuse along by setting up Uno classes that establish easier aliases so modules can be required using their package name rather than the path to their entrypoint. However sometimes determining the entrypoint can feel like a wild guess. I'm sure you know of the wild west of package.json at this point.

GraphQL seems to be a great, specific package to work towards fixing now. Hopefully with every package we make work we gain a thousand more. I'll get on this as soon as I am not in flight somewhere, but I'd really really appreciate your help too!

**Comment by Sunjammer** [comment]
For the record, deps of deps are absolutely intended to be included
